import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "@/context";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JMC-LT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#f8f6f6] ${inter.className}`}>
        <GlobalStateProvider>
          <Navbar />
          <div className="py-28 flex flex-col w-full h-max">
          {children}
          </div>
          <Footer />
        </GlobalStateProvider>
      </body>
    </html>
  );
}
